import { useState } from 'react';
import { X, Download, Copy, Check, Loader2 } from 'lucide-react';

interface Props {
  resultId: string;
  modelKey: 'gpt' | 'claude' | 'gemini';
  modelName: string;
  resumeText: string;
  onClose: () => void;
}

export default function ResumePreviewModal({ resultId, modelKey, modelName, resumeText, onClose }: Props) {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(resumeText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const token = JSON.parse(localStorage.getItem('tailorcv-auth') ?? '{}')?.state?.token;
      const res = await fetch(`/api/v1/ai/results/${resultId}/pdf?model=${modelKey}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!res.ok) throw new Error('Download failed');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `resume-${modelKey}-tailored.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      alert('PDF download failed. Try copying the text instead.');
    } finally {
      setDownloading(false);
    }
  };

  // Render resume text with basic section formatting
  const renderResume = () => {
    const sectionPattern = /^(SUMMARY|OBJECTIVE|EXPERIENCE|EDUCATION|SKILLS|PROJECTS|CERTIFICATIONS|AWARDS|CONTACT|PROFILE|WORK EXPERIENCE|PROFESSIONAL EXPERIENCE|TECHNICAL SKILLS)[\s:]*$/im;

    return resumeText.split('\n').map((line, i) => {
      const trimmed = line.trim();
      if (!trimmed) return <div key={i} className="h-3" />;

      if (sectionPattern.test(trimmed)) {
        return (
          <div key={i} className="mt-5 mb-1">
            <p className="text-[10px] font-bold tracking-widest text-muted-foreground uppercase">{trimmed}</p>
            <hr className="mt-1 border-border" />
          </div>
        );
      }

      if (/^[-•*]\s/.test(trimmed)) {
        return (
          <p key={i} className="text-sm text-foreground pl-3 before:content-['•'] before:mr-2 before:text-muted-foreground">
            {trimmed.replace(/^[-•*]\s*/, '')}
          </p>
        );
      }

      // Short lines with years — likely a job title / date line
      if (trimmed.length < 80 && /\d{4}|present|current/i.test(trimmed)) {
        return <p key={i} className="text-sm font-semibold text-foreground mt-2">{trimmed}</p>;
      }

      return <p key={i} className="text-sm text-foreground">{trimmed}</p>;
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className="bg-background rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col border">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b">
          <div>
            <h2 className="font-semibold text-base">Tailored Resume</h2>
            <p className="text-xs text-muted-foreground">Generated by {modelName}</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-md border hover:bg-accent transition-colors"
            >
              {copied ? <Check size={13} className="text-green-600" /> : <Copy size={13} />}
              {copied ? 'Copied' : 'Copy text'}
            </button>
            <button
              onClick={handleDownload}
              disabled={downloading}
              className="flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-60 transition-colors"
            >
              {downloading ? <Loader2 size={13} className="animate-spin" /> : <Download size={13} />}
              {downloading ? 'Generating...' : 'Download PDF'}
            </button>
            <button onClick={onClose} className="p-1.5 rounded-md hover:bg-accent transition-colors">
              <X size={16} />
            </button>
          </div>
        </div>

        {/* Resume preview */}
        <div className="flex-1 overflow-y-auto px-8 py-6 font-mono leading-relaxed">
          {renderResume()}
        </div>
      </div>
    </div>
  );
}
