import { useState, useCallback, useRef } from 'react';
import { X, Download, Eye, Loader2, RefreshCw } from 'lucide-react';
import { cn } from '@/lib/utils';

type TemplateId = 'classic' | 'jakes' | 'minimal';

const TEMPLATES: { id: TemplateId; label: string; description: string; accent: string }[] = [
  { id: 'jakes',   label: "Jake's",  description: 'The iconic single-column standard', accent: 'border-zinc-800' },
  { id: 'classic', label: 'Classic', description: 'Serif font, centered ornamental header', accent: 'border-stone-500' },
  { id: 'minimal', label: 'Minimal', description: 'Light-weight, generous spacing', accent: 'border-gray-300' },
];

interface Props {
  initialText: string;
  modelName: string;
  candidateName?: string;
  onClose: () => void;
}

export default function ResumeEditorModal({ initialText, modelName, candidateName, onClose }: Props) {
  const [text, setText] = useState(initialText);
  const [template, setTemplate] = useState<TemplateId>('jakes');
  const [previewHtml, setPreviewHtml] = useState('');
  const [previewing, setPreviewing] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [view, setView] = useState<'edit' | 'preview'>('edit');
  const iframeRef = useRef<HTMLIFrameElement>(null);

  const getToken = () =>
    JSON.parse(localStorage.getItem('tailorcv-auth') ?? '{}')?.state?.token ?? '';

  const fetchPreview = useCallback(async () => {
    setPreviewing(true);
    try {
      const res = await fetch('/api/v1/ai/resume/preview', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getToken()}` },
        body: JSON.stringify({ text, template, name: candidateName }),
      });
      const html = await res.text();
      setPreviewHtml(html);
      setView('preview');
    } finally {
      setPreviewing(false);
    }
  }, [text, template]);

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const res = await fetch('/api/v1/ai/resume/pdf', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getToken()}` },
        body: JSON.stringify({ text, template, name: candidateName }),
      });
      if (!res.ok) throw new Error('Failed');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `resume-${template}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      alert('PDF generation failed. Please try again.');
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="bg-background rounded-xl shadow-2xl border w-full max-w-5xl h-[90vh] flex flex-col">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b shrink-0">
          <div>
            <h2 className="font-semibold">Resume Editor</h2>
            <p className="text-xs text-muted-foreground">Generated by {modelName} · edit before downloading</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => view === 'edit' ? fetchPreview() : setView('edit')}
              disabled={previewing}
              className="flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-md border hover:bg-accent transition-colors disabled:opacity-60"
            >
              {previewing
                ? <Loader2 size={13} className="animate-spin" />
                : view === 'edit' ? <Eye size={13} /> : <RefreshCw size={13} />}
              {previewing ? 'Rendering...' : view === 'edit' ? 'Preview' : 'Back to Edit'}
            </button>
            <button
              onClick={handleDownload}
              disabled={downloading}
              className="flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-60 transition-colors"
            >
              {downloading ? <Loader2 size={13} className="animate-spin" /> : <Download size={13} />}
              {downloading ? 'Generating PDF...' : 'Download PDF'}
            </button>
            <button onClick={onClose} className="p-1.5 rounded-md hover:bg-accent transition-colors ml-1">
              <X size={16} />
            </button>
          </div>
        </div>

        {/* Template picker */}
        <div className="flex gap-3 px-6 py-3 border-b bg-muted/30 shrink-0">
          <span className="text-xs font-medium text-muted-foreground self-center mr-1">Template:</span>
          {TEMPLATES.map((t) => (
            <button
              key={t.id}
              onClick={() => { setTemplate(t.id); setView('edit'); }}
              className={cn(
                'flex flex-col px-4 py-2 rounded-lg border-2 text-left transition-all',
                template === t.id
                  ? `${t.accent} bg-background shadow-sm`
                  : 'border-transparent bg-background/60 hover:bg-background'
              )}
            >
              <span className="text-xs font-semibold">{t.label}</span>
              <span className="text-[10px] text-muted-foreground mt-0.5">{t.description}</span>
            </button>
          ))}
        </div>

        {/* Editor / Preview */}
        <div className="flex-1 overflow-hidden">
          {view === 'edit' ? (
            <textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              spellCheck={false}
              className="w-full h-full p-6 font-mono text-sm bg-background resize-none focus:outline-none leading-relaxed"
              placeholder="Resume content will appear here..."
            />
          ) : (
            <iframe
              ref={iframeRef}
              srcDoc={previewHtml}
              className="w-full h-full border-0"
              title="Resume Preview"
            />
          )}
        </div>

        {/* Footer hint */}
        <div className="px-6 py-2.5 border-t bg-muted/20 shrink-0 flex justify-between items-center">
          <p className="text-xs text-muted-foreground">
            {view === 'edit'
              ? 'Edit the content above, then click Preview to see how it looks.'
              : 'Looking good? Hit Download PDF to export.'}
          </p>
          <span className="text-xs text-muted-foreground">{text.length.toLocaleString()} chars</span>
        </div>
      </div>
    </div>
  );
}
